config/routes.rb
CrudDelayedJobs::Engine.routes.draw do
  root 'delayed_jobs#index'
  resources :delayed_jobs
end

app/models/crud_delayed_jobs/application_record.rb
module CrudDelayedJobs
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/crud_delayed_jobs/delayed_job.rb
module CrudDelayedJobs
  class DelayedJob < ApplicationRecord
  end
end

app/controllers/crud_delayed_jobs/application_controller.rb
module CrudDelayedJobs
  class ApplicationController < ActionController::Base
  end
end

app/controllers/crud_delayed_jobs/delayed_jobs_controller.rb
module CrudDelayedJobs
  class DelayedJobsController < ApplicationController
    before_action :set_delayed_job, only: %i[ show edit update destroy ]

    # GET /delayed_jobs
    def index
      @delayed_jobs = DelayedJob.all
    end

    # GET /delayed_jobs/1
    def show
    end

    # GET /delayed_jobs/new
    def new
      @delayed_job = DelayedJob.new
    end

    # GET /delayed_jobs/1/edit
    def edit
    end

    # POST /delayed_jobs
    def create
      @delayed_job = DelayedJob.new(delayed_job_params)

      if @delayed_job.save
        redirect_to @delayed_job, notice: "Delayed job was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /delayed_jobs/1
    def update
      if @delayed_job.update(delayed_job_params)
        redirect_to @delayed_job, notice: "Delayed job was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /delayed_jobs/1
    def destroy
      @delayed_job.destroy
      redirect_to delayed_jobs_url, notice: "Delayed job was successfully destroyed."
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_delayed_job
        @delayed_job = DelayedJob.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def delayed_job_params
        params.require(:delayed_job).permit(:priority, :attempts, :handler, :last_error, :run_at, :locked_at, :failed_at, :locked_by, :queue)
      end
  end
end

app/helpers/crud_delayed_jobs/application_helper.rb
module CrudDelayedJobs
  module ApplicationHelper
  end
end

app/helpers/crud_delayed_jobs/delayed_jobs_helper.rb
module CrudDelayedJobs
  module DelayedJobsHelper
  end
end

app/views/crud_delayed_jobs/delayed_jobs/_delayed_job.html.erb
<div id="<%= dom_id delayed_job %>">

  <% CrudDelayedJobs::DelayedJob.new.attributes.keys.excluding(['created_at', 'updated_at']).each do |prop| %>
    <ul class="list-group">
      <li class="list-group-item">
        <p>
          <strong><%= prop.humanize.capitalize %>:</strong>
          <%= delayed_job.public_send(prop) %>
        </p>
      </li>
    </ul>
  <% end %>
</div>

app/views/crud_delayed_jobs/delayed_jobs/_form.html.erb
<%= form_with(model: delayed_job) do |form| %>
  <% if delayed_job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(delayed_job.errors.count, "error") %> prohibited this delayed_job from being saved:</h2>

      <ul>
        <% delayed_job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Hello</h1>
  <ul class="list-group">
    <li class="list-group-item">
      <div>
        <%= form.label :priority, style: "display: block" %>
        <%= form.number_field :priority %>
      </div>
    </li>
    <li class="list-group-item">
      <div>
        <%= form.label :attempts, style: "display: block" %>
        <%= form.number_field :attempts %>
      </div>
    </li>
    <li class="list-group-item">
      <div>
        <%= form.label :handler, style: "display: block" %>
        <%= form.text_area :handler %>
      </div>
    </li>
    <li class="list-group-item">
      <div>
        <%= form.label :last_error, style: "display: block" %>
        <%= form.text_area :last_error %>
      </div>
    </li>
    <li class="list-group-item">
      <div>
        <%= form.label :run_at, style: "display: block" %>
        <%= form.datetime_field :run_at %>
      </div>
    </li>
    <li class="list-group-item">
      <div>
        <%= form.label :locked_at, style: "display: block" %>
        <%= form.datetime_field :locked_at %>
      </div>
    </li>
    <li class="list-group-item">
      <div>
        <%= form.label :failed_at, style: "display: block" %>
        <%= form.datetime_field :failed_at %>
      </div>
    </li>
    <li class="list-group-item">
      <div>
        <%= form.label :locked_by, style: "display: block" %>
        <%= form.text_field :locked_by %>
      </div>
    </li>
    <li class="list-group-item">
      <div>
        <%= form.label :queue, style: "display: block" %>
        <%= form.text_field :queue %>
      </div>
    </li>
  </ul>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/crud_delayed_jobs/delayed_jobs/edit.html.erb
<h1>Editing delayed job</h1>

<%= render "form", delayed_job: @delayed_job %>

<br>

<div>
  <%= link_to "Show this delayed job", @delayed_job %> |
  <%= link_to "Back to delayed jobs", delayed_jobs_path %>
</div>

app/views/crud_delayed_jobs/delayed_jobs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Delayed jobs</h1>

<div id="delayed_jobs">
  <% @delayed_jobs.each do |delayed_job| %>
    <%= render delayed_job %>
    <p>
      <%= link_to "Show this delayed job", delayed_job %>
    </p>
  <% end %>
</div>

<%= link_to "New delayed job", new_delayed_job_path %>

app/views/crud_delayed_jobs/delayed_jobs/new.html.erb
<h1>New delayed job</h1>

<%= render "form", delayed_job: @delayed_job %>

<br>

<div>
  <%= link_to "Back to delayed jobs", delayed_jobs_path %>
</div>

app/views/crud_delayed_jobs/delayed_jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @delayed_job %>

<div>
  <%= link_to "Edit this delayed job", edit_delayed_job_path(@delayed_job) %> |
  <%= link_to "Back to delayed jobs", delayed_jobs_path %>

  <%= button_to "Destroy this delayed job", @delayed_job, class: 'btn btn-danger', method: :delete %>
</div>

app/views/layouts/crud_delayed_jobs/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crud delayed jobs</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "crud_delayed_jobs/application", "data-turbo-track": "reload" %>

</head>
<body>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>